In [1]:
import pandas as pd
from datetime import datetime

In [310]:
df=pd.read_csv('C:/Users/User/API/2.csv',sep=';',encoding='cp1252')

In [311]:
df.head()

,id,periodid,startdate,enddate,disc,isGk,isShared,isUsn,isEnvd,isBudget,...,mainSystem1420,mainSystem1421,mainSystem1422,mainSystem1423,mainSystem1424,mainSystem1425,mainSystem1426,mainSystem1427,mainSystem1428,notMainSystem
0,3,20861,01.04.2017 0:00,30.04.2017 0:00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,3,20862,01.05.2017 0:00,31.05.2017 0:00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,3,20864,01.06.2017 0:00,30.06.2017 0:00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,3,20865,01.07.2017 0:00,31.07.2017 0:00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,3,20866,01.08.2017 0:00,31.08.2017 0:00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [312]:
df.id.nunique()

4260

In [313]:
unique_id=df.id.unique()
unique_id

array([      3,      29,      42, ..., 1696323, 1696385, 1696463],
      dtype=int64)

In [314]:
df['enddate'] = pd.to_datetime(df.enddate, format='%d.%m.%Y %H:%M')
df['startdate']= pd.to_datetime(df.startdate, format='%d.%m.%Y %H:%M')
df['paid_time']= (pd.to_datetime(df.paidDate, format='%d.%m.%Y %H:%M')-df.startdate).dt.days

In [315]:
client_data=df.groupby('id',as_index=False).agg({'startdate':'max'}).rename({'startdate':'last_month'},axis=1)
df['last_month']=df.groupby(['id'])['startdate'].transform(max)

In [553]:
end_of_time=max(df.last_month)
end_of_time

Timestamp('2019-11-01 00:00:00')

In [317]:
df.paid_time

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
102451     NaN
102452     3.0
102453    10.0
102454    34.0
102455   -15.0
Name: paid_time, Length: 102456, dtype: float64

In [318]:
client_data['is_gone']=(client_data.last_month!='2019-11-01')

In [319]:
client_data.groupby('is_gone').count()

           id  last_month
is_gone
False    2834        2834
True     1426        1426

In [526]:
client_data.head(30)

,id,last_month,is_gone,mainSystem1425max,mainSystem1425min,mainSystem1425cur,mainSystem1418max,mainSystem1418min,mainSystem1418cur,mainSystem1409max,...,incidentReccur,isNssmax,isNssmin,isNsscur,mainSystem1419max,mainSystem1419min,mainSystem1419cur,monthServiceSummax,monthServiceSummin,monthServiceSumcur
0,3,2017-12-01,True,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN
1,29,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,32752.00
2,42,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.017027,35063.03
3,63,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,24700.00
4,65,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN
5,102,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.016086,12646.87
6,108,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.016113,3983.62
7,123,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,18730.00
8,128,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN
9,132,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.387566,10289.16
10,137,2019-11-01,False,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,15437.00
11,185,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN
12,211,2018-09-01,True,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN
13,246,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.032993,7076.00
14,251,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.039846,6209.96
15,319,2017-12-01,True,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN
16,338,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,3000.00
17,342,2019-08-01,True,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN
18,361,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,7186.00
19,447,2019-11-01,False,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,13406.51
20,535,2017-12-01,True,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN
21,538,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,8310.00
22,555,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,16033.00
23,557,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.038161,61566.99
24,589,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,22695.80
25,612,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,40773.70
26,640,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN
27,710,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN
28,711,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN
29,712,2019-11-01,False,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.000000,14406.00

In [321]:
excepted_columns=['paidDate','startdate','enddate','last_month']

In [322]:
col

'sixMonthDebt'

In [ ]:
eps=1e-9
columns=list(set(list(df))-set('id'))
for id in unique_id:
    print(id,end=' ')
    for col in columns:
        if col in excepted_columns:
            continue
#         if df.loc[df.id==id].last_month.max()<end_of_time:
#             max_value=df.loc[(df.id==id)&(df.startdate>df.last_month-pd.Timedelta(days=182))][col].astype(float).max()
#             min_value=df.loc[(df.id==id)&(df.startdate>df.last_month-pd.Timedelta(days=182))][col].astype(float).min()
#             cur_value=df.loc[(df.id==id)&(df.last_month==df.startdate)][col].astype(float).max()
#         else:
        max_value=df.loc[(df.id==id)&(df.startdate>df.last_month-pd.Timedelta(days=182+45))&
                                         (df.startdate<end_of_time)][col].astype(float).max()
        min_value=df.loc[(df.id==id)&(df.startdate>df.last_month-pd.Timedelta(days=182+45))&
                                         (df.startdate<end_of_time)][col].astype(float).min()
        cur_value=df.loc[(df.id==id)&(df.startdate>df.last_month-pd.Timedelta(days=45))&
                                         (df.startdate<end_of_time)][col].astype(float).max()
            

        client_data.loc[client_data.id==id,col+'max']=(cur_value+eps)/(max_value+eps)
        client_data.loc[client_data.id==id,col+'min']=(cur_value+eps)/(min_value+eps)
        client_data.loc[client_data.id==id,col+'cur']=cur_value

3 29 42 63 65 102 108 123 128 132 137 185 211 246 251 319 338 342 361 447 535 538 555 557 589 612 640 710 711 712 722 836 851 877 894 909 914 930 962 968 969 1064 1103 1150 1211 1276 1325 1337 1345 1353 1355 1423 1458 1568 1602 1643 1776 1820 1835 1890 1907 1935 2024 2032 2055 2064 2065 2067 2071 2073 2074 2075 2076 2077 2078 2090 2129 2130 2132 2143 2145 2148 2152 2163 2244 2260 2302 2365 2368 2369 2391 2411 2416 2417 2455 2509 2532 2535 2547 2549 2596 2670 2742 2748 2787 2798 2805 2819 2820 2821 2840 2845 2871 2874 2884 2968 3012 3208 3210 3212 3227 3242 3250 3309 3342 3385 3503 3679 3815 3872 3915 4021 4026 4043 4121 4134 4149 4185 4191 4193 4194 4218 4303 4394 4412 4426 4458 4486 4488 4515 4518 4536 4541 4543 4553 4570 4614 4714 4715 4718 4725 4730 4741 4752 4766 4778 4781 4798 4800 4801 4804 4807 4825 4827 4828 4829 4842 4855 4861 4862 4872 4883 4886 4891 4950 4982 5003 5012 5016 5035 5042 5094 5111 5129 5134 5193 5222 5230 5285 5293 5297 5299 5314 5327 5331 5336 5342 5357 5395 5414 5418 5428 5446 5453 5479 5488 5538 5552 5561 5582 5589 5606 5610 5639 5646 5671 5675 5691 5693 5697 5703 5717 5776 5783 5784 5789 5792 5796 5841 5850 5854 5860 5866 5875 5889 5923 5934 5937 5944 5975 5998 6088 6143 6144 6157 6185 6205 6212 6223 6224 6230 6257 6302 6312 6326 6328 6333 6336 6339 6340 6353 6392 6411 6431 6467 6472 6536 6559 6562 6566 6567 6574 6580 6582 6595 6604 6608 6609 6623 6624 6644 6648 6657 6667 6674 6676 6701 6704 6707 6726 6728 6748 6772 6778 6799 6813 6815 6823 6849 6859 6862 6877 6886 6890 6891 6895 6901 6906 6907 6911 6927 6939 6940 6941 6946 6948 6992 7012 7024 7027 7030 7039 7042 7044 7051 7053 7055 7060 7062 7067 7072 7073 7076 7077 7080 7111 7117 7118 7127 7129 7142 7148 7153 7154 7164 7171 7176 7181 7182 7188 7189 7190 7198 7200 7207 7210 7214 7216 7218 7219 7220 7223 7225 7227 7228 7229 7230 7231 7232 7233 7234 7235 7236 7238 7246 7282 7292 7309 7312 7314 7315 7317 7318 7320 7321 7331 7332 7335 7339 7344 7347 7350 7366 7379 7395 7400 7405 7412 7413 7421 7423 7424 7429 7430 7431 7436 7443 7445 7448 7461 7464 7482 7484 7492 7495 7504 7514 7516 7517 7525 7526 7562 7577 7579 7589 7596 7598 7627 7632 7634 7638 7641 7648 7660 7683 7687 7688 7708 7710 7712 7722 7723 7724 7729 7748 7764 7776 7797 7798 7854 7862 7866 7868 7870 7872 7874 7881 7885 7888 7896 7904 7912 7916 7918 7920 7922 7927 7942 7959 7964 7982 7988 8003 8004 8008 8012 8018 8022 8027 8039 8040 8092 8093 8098 8110 8112 8121 8123 8137 8145 8149 8159 8165 8177 8189 8193 8197 8210 8213 8231 8241 8259 8263 8265 8268 8280 8281 8285 8288 8297 8302 8305 8306 8314 8338 8359 8362 8369 8377 8379 8407 8418 8444 8448 8451 8453 8457 8460 8472 8473 8475 8491 8494 8496 8507 8512 8516 8530 8538 8545 8552 8554 8561 8563 8592 8599 8620 8624 8629 8634 8636 8649 8656 8657 8659 8688 8693 8708 8712 8734 8751 8760 8761 8771 8792 8794 8807 8811 8814 8822 8829 8839 8840 8845 8847 8867 8869 8870 8871 8891 8908 8910 8913 8914 8919 8935 8941 8943 8952 8953 8983 8998 9000 9003 9005 9006 9025 9029 9033 9062 9064 9076 9077 9078 9103 9118 9121 9122 9126 9134 9137 9143 9145 9153 9183 9185 9186 9191 9218 9232 9234 9235 9252 9284 9285 9286 9287 9293 9323 9330 9335 9341 9343 9344 9348 9351 9365 9369 9381 9396 9408 9432 9439 9443 9446 9449 9451 9453 9456 9463 9465 9466 9469 9472 9473 9478 9483 9491 9512 9517 9521 9524 9538 9540 9546 9577 9586 9587 9588 9589 9590 9591 9592 9593 9598 9599 9607 9608 9609 9618 9619 9620 9621 9622 9623 9624 9625 9626 9627 9629 9630 9631 9634 9635 9640 9644 9645 9646 9653 9654 9655 9656 9657 9660 9661 9662 9663 9664 9665 9666 9673 9674 9675 9676 9677 9686 9708 9711 9715 9718 9722 9724 9730 9754 9781 9796 9798 9803 9831 9834 9849 9858 9880 9909 9910 9976 10005 10010 10039 10044 10058 10070 10112 10114 10122 10140 10167 10180 10198 10262 10276 10289 10297 10331 10333 10339 10341 10343 10372 10374 10378 10394 10402 10404 10408 10416 10423 10425 10429 10460 10464 10473 10481 10491 10509 10512 10517 10520 10529 10540 10560 10610 10612 10638 10650 10664 10683 10707 10717 10725 10774 10775 10780 10783 10840 10841 10842 10846 10900 10911 10922 10927 10929 10940 10941 10950 10966 11022 11073 11127 11132 11137 11167 11237 11244 11246 11250 11286 11288 11295 11298 11334 11337 11347 11350 11383 11410 11423 11473 11475 11480 11486 11489 11496 11498 11502 11503 11508 11512 11513 11539 11571 11583 11650 11658 11668 11680 11687 11706 11729 11742 11775 11787 11789 11817 11825 11833 11865 11895 11907 11913 11914 11918 11925 11947 11948 11949 11950 11951 11953 11954 11955 11956 11957 11958 11959 11960 11962 11963 11964 11965 11966 11967 11968 11969 11970 11971 11972 11973 11974 11975 11976 11977 11978 11979 11980 11981 11983 11984 11985 11986 11987 11988 11989 11990 11991 11992 11993 11994 11995 11996 11997 12047 12048 12075 12129 12160 12187 12189 12235 12245 12260 12264 12292 12313 12324 12327 12373 12408 12410 12432 12482 12507 12537 12567 12588 12626 12654 12684 12722 12727 12731 12743 12897 12908 12909 12910 12939 12954 12995 13001 13046 13058 13087 13142 13143 13686 13691 13723 13763 13770 13785 13794 13796 13798 13804 13824 13840 13850 13851 13860 13872 13880 13905 13923 13927 13937 13938 13939 13941 13942 13943 13946 13968 13972 13980 14005 14015 14033 14051 14055 14059 14067 14085 14120 14126 14129 14137 14138 14140 14160 14195 14204 14214 14215 14216 14225 14231 14233 14237 14238 14255 14274 14276 14327 14337 14350 14357 14367 14387 14392 14411 14438 14456 14500 14517 14519 14540 14575 14576 14619 14636 14649 14675 14706 14769 14801 14875 14904 14940 14968 15002 15034 15079 15243 15287 15344 15380 15425 15454 15459 15470 15477 15496 15552 15605 15631 15643 15665 15666 15713 15784 15847 15879 15906 15913 15918 15922 15925 15972 16016 16049 16051 16067 16072 16126 16127 16144 16164 16182 16219 16228 16235 16238 16239 16240 16241 16242 16243 16244 16256 16272 16311 16312 16347 16384 16387 16394 16395 16434 16442 16461 16512 16607 16610 16611 16627 16644 16653 16655 16669 16670 16671 16672 16673 16674 16675 16676 16677 16678 16679 16680 16681 16682 16683 16684 16685 16686 16687 16688 16689 16690 16691 16692 16693 16694 16695 16696 16697 16698 16699 16700 16701 16702 16704 16705 16706 16709 16710 16713 16715 16727 16732 16733 16735 16737 16750 16762 16780 16795 16807 16808 16811 16816 16819 16821 16825 16830 16834 16900 16950 16951 16974 16988 16997 17008 17009 17010 17012 17013 17016 17018 17048 17066 17068 17069 17076 17087 17099 17140 17148 17151 17153 17173 17192 17203 17214 17219 17238 17239 17243 17244 17248 17264 17269 17305 17313 17315 17318 17319 17321 17322 17370 17371 17374 17397 17398 17405 17412 17416 17421 17427 17437 17443 17449 17450 17455 17459 17468 17470 17474 17475 17476 17477 17478 17479 17482 17490 17491 17492 17494 17497 17499 17501 17504 17508 17529 17530 17531 17542 17552 17569 17576 17606 17643 17650 17668 17687 17690 17706 17740 17788 17794 17805 17814 17823 17824 17855 17867 17871 17879 17883 17915 17927 17929 17958 17966 17985 18012 18067 18068 18071 18108 18155 18159 18167 18176 18180 18181 18182 18189 18197 18247 18252 18253 18254 18255 18257 18258 18259 18260 18261 18262 18263 18264 18265 18266 18267 18268 18284 18292 18293 18294 18295 18296 18297 18298 18299 18301 18302 18303 18304 18311 18398 18400 18401 18404 18416 18423 18462 18476 18477 18552 18554 18560 18577 18602 18621 18641 18642 18679 18696 18704 18771 18772 18784 18785 18891 18897 18966 18972 19032 19068 19073 19148 19174 19208 19212 19244 19281 19291 19295 19299 19302 19311 19319 19320 19331 19354 19369 19396 19461 19485 19519 19547 19601 19630 19735 19742 19788 19802 19823 19841 19947 19993 20000 20001 20003 20004 20007 20024 20034 20038 20049 20050 20062 20116 20234 20251 20253 20267 20302 20303 20322 20330 20345 20347 20349 20354 20374 20415 20421 20458 20473 20522 20583 20602 20637 20667 20703 20724 20739 20740 20741 20747 20800 20802 20811 20823 20832 20848 20872 20880 20882 20886 20888 20902 20908 20916 20940 20944 20947 20990 20993 20996 20999 21000 21001 21002 21003 21004 21005 21009 21018 21030 21032 21035 21036 21037 21038 21045 21070 21097 21099 21107 21146 21221 21228 21231 21275 21284 21286 21289 21292 21296 21297 21298 21300 21305 21306 21333 21341 21361 21364 21370 21393 21396 21402

21409 21414 21418 21459 21464 21465 21484 21496 21497 21498 21499 21511 21514 21580 21596 21597 21600 21601 21607 21611 21626 21627 21637 21638 21651 21660 21661 21681 21686 21706 21722 21750 21751 21763 21766 21780 21783 21809 21812 21813 21816 21821 21867 21900 21902 21936 21947 21948 21994 22035 22039 22069 22071 22126 22129 22132 22133 22134 22135 22142 22146 22149 22152 22172 22179 22201 22222 22228 22236 22238 22250 22255 22294 22315 22334 22366 22388 22397 22454 22469 22480 22481 22482 22483 22493 22517 22544 22551 22565 22591 22601 22647 22654 22745 22778 22783 22822 22836 22871 22919 22925 22992 23105 23129 23130 23131 23174 23265 23288 23329 23358 23363 23364 23369 23390 23445 23466 23505 23544 23599 23632 23633 23634 23637 23659 23718 23720 23758 23762 23766 23767 23772 23775 23778 23815 23817 23825 23864 23877 23888 23889 23897 23898 23911 23916 23923 23927 23937 23938 23945 23952 23962 23995 24093 24124 24136 24185 24186 24207 24228 24252 24284 24311 24327 24353 24391 24410 24411 24515 24553 24560 24600 24632 24658 24685 24694 24716 24720 24725 24727 24733 24734 24736 24765 24783 24784 24790 24796 24807 24823 24825 24826 24852 24853 24854 24855 24856 24876 24905 24925 24926 24935 24945 24955 24985 25002 25007 25015 25053 25099 25104 25106 25121 25127 25131 25164 25201 25231 25232 25240 25241 25242 25243 25244 25245 25259 25292 25311 25323 25335 25365 25376 25384 25386 25454 25481 25492 25493 25494 25513 25527 25531 25562 25588 25590 25591 25594 25600 25601 25634 25644 25651 25662 25731 25732 25733 25734 25735 25749 25750 25760 25782 25799 25800 25801 25803 25806 25847 25862 25899 25904 25905 25930 25962 25969 26009 26026 26032 26033 26034 26035 26036 26038 26039 26052 26058 26074 26095 26104 26134 26145 26190 26191 26200 26222 26230 26263 26264 26283 26284 26285 26286 26287 26288 26289 26290 26291 26294 26295 26296 26297 26298 26299 26300 26346 26350 26387 26389 26404 26409 26413 26425 26452 26453 26462 26463 26498 26544 26573 26604 26629 26664 26670 26697 26722 26747 26753 26755 26756 26757 26758 26759 26760 26761 26769 26779 26788 26922 26925 26968 26975 26997 27019 27056 27058 27059 27060 27093 27124 27131 27132 27137 27165 27187 27200 27222 27263 27286 27288 27290 27427 27436 27445 27546 27547 27555 27579 27587 27593 27608 27621 27640 27718 27880 27884 27908 27914 27935 27942 27957 27966 28007 28019 28046 28294 28302 28338 28360 28369 28384 28424 28437 28511 28533 28602 28651 28671 28681 28707 28722 28747 28799 28809 28884 28899 28901 28919 28972 28973 28981 28996 28997 29005 29058 29076 29094 29101 29185 29189 29203 29227 29249 29274 29296 29307 29412 29421 29464 29480 29484 29498 29510 29516 29532 29540 29544 29580 29584 29590 29622 29646 29665 29680 29758 29792 29815 29828 29836 29841 29859 29877 29881 29899 29979 29996 30018 30020 30022 30060 30061 30069 30073 30102 30103 30112 30164 30205 30251 30281 30316 30367 30405 30433 30448 30454 30461 30548 30552 30600 30604 30660 30663 30668 30669 30693 30793 30801 30802 30837 30839 30840 30841 30842 30843 30844 30845 30846 30865 30882 30883 30884 30904 30909 30943 31023 31038 31073 31099 31109 31145 31182 31192 31198 31209 31245 31261 31264 31288 31292 31325 31375 31392 31396 31398 31403 31419 31497 31514 31537 31606 31607 31615 31715 31734 31804 31808 31831 31874 32041 32109 32199 32215 32220 32227 32261 32278 32304 32309 32317 32328 32352 32360 32387 32392 32415 32444 32450 32493 32494 32495 32497 32500 32531 32534 32553 32562 32575 32623 32644 32651 32656 32660 32672 32718 32739 32746 32747 32762 32763 32818 32843 32846 32849 32905 32906 32915 32921 32944 32993 33086 33098 33152 33163 33233 33257 33290 33293 33298 33342 33359 33465 33485 33520 33539 33595 33599 33605 33695 33729 33751 33774 33787 33794 33799 33826 33923 34001 34035 34119 34122 34129 34220 34221 34222 34226 34259 34288 34354 34362 34364 34400 34420 34435 34439 34467 34468 34469 34478 34506 34516 34555 34564 34599 34601 34610 34628 34647 34667 34668 34669 34674 34706 34748 34864 34887 34908 34997 34998 35000 35003 35009 35016 35157 35276 35306 35309 35317 35319 35349 35358 35436 35462 35468 35502 35519 35521 35549 35573 35629 35632 35737 35752 35891 35961 36056 36058 36170 36200 36203 36263

In [ ]:
cur_value.describe()

In [ ]:
client_data.shape

In [ ]:
client_data1=client_data.fillna(0)

In [ ]:
from sklearn.model_selection import train_test_split
import random
import numpy as np
import torch
from torch.optim import Adam, lr_scheduler

random.seed(1234)
np.random.seed(1234)
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)
torch.backends.cudnn.deterministic = True

In [ ]:
X=client_data1.drop(['is_gone','last_month','id'],axis=1)
y=client_data1.is_gone

In [ ]:
X.shape,y.shape

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape

In [ ]:
X_train=torch.DoubleTensor(X_train.values)
X_test=torch.DoubleTensor(X_test.values)
y_train=torch.LongTensor(y_train.values)
y_test=torch.LongTensor(y_test.values)

In [ ]:
X_train.shape

In [ ]:
batch_size=3408
lr=1e-4
num_epoch=3000
step_size=200
gamma=0.7

In [ ]:
class API_net(torch.nn.Module):
    def __init__(self):
        super(API_net,self).__init__()
        self.fc1=torch.nn.Linear(264,500)
        self.act1=torch.nn.ReLU()
        self.fc2=torch.nn.Linear(500,500)
        self.act2=torch.nn.Tanh()
        self.fc3=torch.nn.Linear(500,2)
    
    def forward(self,x):
        x=self.fc1(x)
        x=self.act1(x)
        x=self.fc2(x)
        x=self.act2(x)
        x=self.fc3(x)
        return x

model=API_net().double()

In [ ]:
model=API_net().double()
device=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
loss=torch.nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=lr)
scheduler = lr_scheduler.StepLR(optimizer,
                                step_size=step_size,
                                gamma=gamma)
    
train_accuracy_history=[]
train_loss_history=[]
test_accuracy_history=[]
test_loss_history=[]
    
for epoch in range(num_epoch):
    print()
    print('Epoch {}/{}:'.format(epoch, num_epoch - 1), flush=True)
        
    for phase in ['train','test']:
        if phase=='train':
            running_loss = 0
            running_acc = 0
            order=np.random.permutation(len(X_train))
            for start_index in range(0,len(X_train),batch_size):
                optimizer.zero_grad()
                net.train()
                batch_indexes=order[start_index:start_index+batch_size]
                X_batch=X_train[batch_indexes].to(device)
                y_batch=y_train[batch_indexes].to(device)
                preds=model.forward(X_batch)
                loss_value=loss(preds,y_batch)
                preds_class=preds.argmax(dim=1)
                loss_value.backward()
                optimizer.step()
                running_loss+=loss_value.data.cpu()
                running_acc+=(preds_class==y_batch).float().mean().data.cpu()
            train_accuracy_history.append(running_acc/(len(X_train)/batch_size))
            train_loss_history.append(running_loss/(len(X_train)/batch_size))
        else:
#             continue
            net.eval()
            preds=model.forward(X_test)
            loss_value=loss(preds,y_test).data
            preds_class=preds.argmax(dim=1)
            test_accuracy_history.append((preds_class==y_test).float().mean().data)
            test_loss_history.append(loss_value)
    print('train loss ',train_loss_history[-1])
    print('train acc  ',train_accuracy_history[-1])
    print('test loss  ',test_loss_history[-1])
    print('test acc   ',test_accuracy_history[-1])

In [ ]:
from matplotlib import pyplot as plt
history=[train_accuracy_history,train_loss_history,test_accuracy_history,test_loss_history]
titles = ['Train Accuracy', 'Train Loss', 'Val Accuracy', 'Val Loss']
plt.figure(figsize=(10, 10))
for i, image in enumerate(history):
    plt.subplot(2, 2, i+1)
    plt.title(titles[i])
    plt.grid()
    if i == 0 or i == 1:
        color = 'b'
    else:
        color = 'orange'
    plt.plot(image,c=color, label= 'mean: %.2f' % np.array(image).mean())
    plt.legend(loc='best')
plt.show()

# Рисуем совмещенные графики  Accuracy и Loss для Тренеровочной и валидационной выборки
titles_ = ['Accuracy','Loss']
plt.figure(figsize=(10, 5))
k=0
for i in range(2):
    plt.subplot(1, 2, i+1)
    plt.plot(history[0+k], label='Tain', c='b')
    plt.plot(history[2+k], label='Val', c='orange')
    plt.title(titles_[i])
    plt.grid()
    plt.legend(loc='best')
    k += 1

In [ ]:
preds=model.forward(X_test)
m = torch.nn.Softmax(dim=1)
y_predicted=m(preds)
y_predicted=y_predicted.detach().numpy()
y_predicted

In [ ]:
y_predicted[:,1].shape,y_test.shape

In [ ]:
y_predicted[:,1]

In [ ]:
from sklearn.metrics import roc_curve, auc
fpr, tpr, thresholds = roc_curve(y_test, y_predicted[:,1])
roc_auc= auc(fpr, tpr)
plt.figure()
plt.plot(fpr, tpr, color='darkorange', label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")
plt.show()